# Generated by Django 2.0.6 on 2019-04-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doubanmovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=50, verbose_name='电影名')),
                ('info', models.CharField(db_column=' info', max_length=50, verbose_name='导演名')),
                ('info_1', models.CharField(db_column=' info_1', max_length=50, verbose_name='演员名')),
                ('date', models.CharField(db_column='date', max_length=50, verbose_name='上映日期')),
                ('country', models.CharField(db_column=' country', max_length=50, verbose_name='城市')),
                ('geners', models.CharField(db_column=' geners', max_length=50, verbose_name='类型')),
                ('rate', models.CharField(db_column=' rate', max_length=50, verbose_name='分数')),
                ('comCount', models.CharField(db_column=' comCount', max_length=50, verbose_name='评论人数')),
            ],
            options={
                'db_table': 'doubanmovie',
            },
        ),
    ]
